### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by YangJian1994** [rocketeerli/Computer-VisionandAudio-Lab#1]
博主，你好，我最近也在做这个实验，想问一下，你的程序中的“21”是什么意思，经验值吗？能加QQ交流一下吗？我的QQ是571228207，谢谢！

**Comment by rocketeerli** [comment]
这个参数是我根据样本调的，是为了使第一次检测后的两段浊音之间的距离不要太小，如果距离很小的话（这里就是小于21）就可以确定这不是端点，不能分成两段语音。你可以使用其他参数测试一下，如果太小的话，会出现其他问题
